"""Milestone-1 coverage report: how much of the Google universe we could tie to official records,
how, and how trustworthy those links are. Written to output/<month>/coverage.md."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

import duckdb


def _table(con: duckdb.DuckDBPyConnection, sql: str, params: Sequence[object] | None = None) -> str:
    rel = con.execute(sql, params or [])
    cols = [d[0] for d in rel.description]
    rows = rel.fetchall()
    fmt = lambda v: "" if v is None else (f"{v:,.1f}" if isinstance(v, float) else str(v))  # noqa: E731
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    lines += ["| " + " | ".join(fmt(v) for v in r) + " |" for r in rows]
    return "\n".join(lines)


def coverage_report(con: duckdb.DuckDBPyConnection, run_month: str, out_dir: Path) -> Path:
    m = [run_month]
    sections = [
        f"# Coverage report - run {run_month}",
        "Generated by `shadowleads report`. Every number below is reproducible from the warehouse.",
        "## 1. Google sweep",
        _table(
            con,
            "SELECT status, count(*) AS cells, sum(n_results) AS results "
            "FROM stg.google_sweep WHERE run_month = ? GROUP BY 1 ORDER BY 2 DESC",
            m,
        ),
        "## 2. Places in scope per category",
        _table(
            con,
            """SELECT coalesce(category, '(none)') AS category, count(*) AS places,
                      count(*) FILTER (WHERE in_scope) AS in_scope,
                      count(*) FILTER (WHERE self_service) AS self_service_wash,
                      sum(user_rating_count) FILTER (WHERE in_scope) AS reviews
               FROM core.place_snapshot WHERE run_month = ? GROUP BY 1 ORDER BY 2 DESC""",
            m,
        ),
        "Out-of-scope reasons:",
        _table(
            con,
            "SELECT out_of_scope_reason AS reason, count(*) AS places FROM core.place_snapshot "
            "WHERE run_month = ? AND NOT in_scope GROUP BY 1 ORDER BY 2 DESC",
            m,
        ),
        "## 3. Linking outcome per category",
        _table(
            con,
            """SELECT p.category,
                      count(*) AS places,
                      count(*) FILTER (WHERE l.status = 'linked') AS linked,
                      round(100.0 * count(*) FILTER (WHERE l.status = 'linked') / count(*), 1) AS pct_linked,
                      count(*) FILTER (WHERE l.confidence = 'HIGH') AS high,
                      count(*) FILTER (WHERE l.status = 'ambiguous') AS ambiguous,
                      count(*) FILTER (WHERE l.status = 'unmatched') AS unmatched,
                      round(100.0 * sum(p.user_rating_count) FILTER (WHERE l.status = 'linked')
                            / sum(p.user_rating_count), 1) AS pct_reviews_linked
               FROM core.place_snapshot p JOIN core.place_entity_link l USING (run_month, place_id)
               WHERE p.run_month = ? AND p.in_scope GROUP BY 1 ORDER BY 1""",
            m,
        ),
        "### By method",
        _table(
            con,
            """SELECT coalesce(method, status || ': ' || reason) AS method_or_reason, confidence,
                      count(*) AS places
               FROM core.place_entity_link WHERE run_month = ? GROUP BY 1, 2 ORDER BY 3 DESC LIMIT 25""",
            m,
        ),
        "## 4. Link validation",
        "`confirmed` = at least one independent source (VMVT premises, company/VAT code on the "
        "business's own website, company code in Google snippets, directory URL) names the same "
        "company; `conflict` = independent evidence names a different company only.",
        _table(
            con,
            """SELECT method, count(*) AS links,
                      count(*) FILTER (WHERE validation_status LIKE 'confirmed%') AS confirmed,
                      count(*) FILTER (WHERE validation_status = 'conflict') AS conflict,
                      count(*) FILTER (WHERE validation_status = 'unverified') AS unverified,
                      round(100.0 * count(*) FILTER (WHERE validation_status LIKE 'confirmed%')
                            / nullif(count(*) FILTER (WHERE validation_status <> 'unverified'), 0), 1)
                        AS precision_where_checked_pct,
                      count(*) FILTER (WHERE usable) AS usable_for_priority
               FROM core.link_validation WHERE run_month = ? GROUP BY 1 ORDER BY 2 DESC""",
            m,
        ),
        "## 5. Declared-data coverage of linked entities",
        _table(
            con,
            """SELECT main_category AS category, count(*) AS entities,
                      count(*) FILTER (WHERE has_vmi_record) AS with_vmi_taxes,
                      count(*) FILTER (WHERE has_sodra_record) AS with_sodra,
                      count(*) FILTER (WHERE revenue_fy IS NOT NULL) AS with_revenue,
                      count(*) FILTER (WHERE revenue_fy >= tax_year) AS with_revenue_last_fy,
                      count(*) FILTER (WHERE owner_operated) AS owner_operated_mb_ii,
                      count(*) FILTER (WHERE vat_registered) AS vat_registered,
                      count(*) FILTER (WHERE shared_premises) AS shared_premises,
                      count(*) FILTER (WHERE new_entity) AS new_entity
               FROM mart.entity_activity WHERE run_month = ? GROUP BY 1 ORDER BY 1""",
            m,
        ),
        "## 6. Busiest places we could NOT link (streetlight-bias check)",
        _table(
            con,
            """SELECT p.name, p.category, p.user_rating_count AS reviews, l.status, l.reason
               FROM core.place_snapshot p JOIN core.place_entity_link l USING (run_month, place_id)
               WHERE p.run_month = ? AND p.in_scope AND l.status <> 'linked'
               ORDER BY p.user_rating_count DESC NULLS LAST LIMIT 15""",
            m,
        ),
    ]
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "coverage.md"
    path.write_text("\n\n".join(sections) + "\n", encoding="utf-8")
    return path
